/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/measurement": {
    /** Get measurements by type */
    get: {
      parameters: {
        query: {
          type: string;
          sort?: "asc" | "desc";
          offset?: number;
          limit?: number;
        };
      };
      responses: {
        /** @description Measurements retrieved successfully */
        200: {
          content: {
            "application/json": components["schemas"]["MeasurementsResponse"];
          };
        };
        /** @description Validation error */
        400: {
          content: never;
        };
      };
    };
    /** Update a measurement */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["Measurement"];
        };
      };
      responses: {
        /** @description Measurement updated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["MeasurementResponse"];
          };
        };
        /** @description Validation error */
        400: {
          content: never;
        };
        /** @description Measurement not found or not authorized */
        404: {
          content: never;
        };
      };
    };
    /** Add a new measurement */
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["Measurement"];
        };
      };
      responses: {
        /** @description Measurement added successfully */
        200: {
          content: {
            "application/json": components["schemas"]["MeasurementResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description User not found */
        409: {
          content: never;
        };
      };
    };
    /** Delete a measurement */
    delete: {
      parameters: {
        query: {
          id: string;
        };
      };
      responses: {
        /** @description Measurement deleted successfully */
        200: {
          content: {
            "application/json": components["schemas"]["DeleteResponse"];
          };
        };
        /** @description Measurement not found or not authorized */
        404: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Measurement: {
      /** @description Timestamp of the measurement (defaults to current time) */
      timestamp?: number;
      /** @description Type of measurement */
      type: string;
      /** @description Additional metadata for the measurement */
      meta?: {
        [key: string]: string | number;
      };
    };
    MeasurementResponse: {
      success?: boolean;
      measurement?: components["schemas"]["Measurement"];
    };
    MeasurementsResponse: {
      success?: boolean;
      measurements?: components["schemas"]["Measurement"][];
    };
    DeleteResponse: {
      success?: boolean;
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
